// Every site below is live in production and was built by Ritesh Kumar Giri,
// either directly or through NextGen Fusion. `caseStudy` points at an internal
// /projects/<slug> page where a written case study exists; the rest link out to
// the live site. Screenshots live in /public/assets/directory/<slug>.webp and are
// captured from the real site, never stock imagery.
export const directoryCategories = [
  "All",
  "Fashion & Clothing",
  "Beauty & Wellness",
  "Jewelry",
  "Service-based",
  "Food & Beverage",
  "Gifts",
  "Home & Decor",
  "Custom",
  "Other",
];

export const directoryProjects = [
  {
    slug: "maribiz-ai",
    name: "MariBiz",
    domain: "maribiz.ai",
    url: "https://maribiz.ai/",
    category: "Custom",
    caseStudy: "maribiz",
  },
  {
    slug: "tatvivahtrends-com",
    name: "TatVivah Trends",
    domain: "tatvivahtrends.com",
    url: "https://tatvivahtrends.com/",
    category: "Fashion & Clothing",
    caseStudy: "tatvivahtrends",
  },
  {
    slug: "vayue-in",
    name: "Vayué",
    domain: "vayue.in",
    url: "https://vayue.in/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "poshwave-co-in",
    name: "PoshWave",
    domain: "poshwave.co.in",
    url: "https://poshwave.co.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "nuaura-co",
    name: "Nuáura",
    domain: "nuaura.co",
    url: "https://nuaura.co/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "soukprofumi-it",
    name: "Souk Profumi",
    domain: "soukprofumi.it",
    url: "https://soukprofumi.it/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "atharavelectroplaters-com",
    name: "Atharav Electroplaters",
    domain: "atharavelectroplaters.com",
    url: "https://atharavelectroplaters.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "kalamohini-in",
    name: "Kala Mohini",
    domain: "kalamohini.in",
    url: "https://kalamohini.in/",
    category: "Fashion & Clothing",
    caseStudy: "kalamohini",
  },
  {
    slug: "tulsiinstitute-in",
    name: "Tulsi Institute",
    domain: "tulsiinstitute.in",
    url: "https://tulsiinstitute.in/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "rumaneroyale-com",
    name: "Rumäne Royale",
    domain: "rumaneroyale.com",
    url: "https://rumaneroyale.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "aalaenatural-com",
    name: "Aalae Natural",
    domain: "aalaenatural.com",
    url: "https://aalaenatural.com/home/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "slowy-in",
    name: "Slowy",
    domain: "slowy.in",
    url: "https://slowy.in/",
    category: "Jewelry",
    caseStudy: null,
  },
  {
    slug: "royalvaster-co-uk",
    name: "Royal Vastar",
    domain: "royalvaster.co.uk",
    url: "https://royalvaster.co.uk/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "keoolix-in",
    name: "Keoolix",
    domain: "keoolix.in",
    url: "https://keoolix.in/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "bholawelding-com",
    name: "Bhola Welding",
    domain: "bholawelding.com",
    url: "https://bholawelding.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "orangelilies-com",
    name: "Orange Lilies",
    domain: "orangelilies.com",
    url: "https://orangelilies.com/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "jayantitextiles-in",
    name: "Jayanti Textiles",
    domain: "jayantitextiles.in",
    url: "https://jayantitextiles.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "mahhika-com",
    name: "Mahhika",
    domain: "mahhika.com",
    url: "https://mahhika.com/",
    category: "Fashion & Clothing",
    caseStudy: "mahhika",
  },
  {
    slug: "suratcollection-com",
    name: "Surat Collection",
    domain: "suratcollection.com",
    url: "https://suratcollection.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "vostra-in",
    name: "Vostra",
    domain: "vostra.in",
    url: "https://vostra.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "chikusmile-com",
    name: "Chikusmile",
    domain: "chikusmile.com",
    url: "http://chikusmile.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "tatvivah-in",
    name: "TatVivah",
    domain: "tatvivah.in",
    url: "https://tatvivah.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "vyorajewelhouse-com",
    name: "Vyorajewelhouse",
    domain: "vyorajewelhouse.com",
    url: "https://vyorajewelhouse.com/",
    category: "Jewelry",
    caseStudy: null,
  },
  {
    slug: "samaraha-com",
    name: "Samaraha",
    domain: "samaraha.com",
    url: "https://samaraha.com/",
    category: "Fashion & Clothing",
    caseStudy: "samaraha",
  },
  {
    slug: "saurally-com",
    name: "Saurally",
    domain: "saurally.com",
    url: "https://saurally.com/",
    category: "Other",
    caseStudy: "saurally",
  },
  {
    slug: "unitexfashion-in",
    name: "Unitexfashion",
    domain: "unitexfashion.in",
    url: "http://unitexfashion.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "newsaraswatisareecentre-in",
    name: "New Saraswati Saree Centre",
    domain: "newsaraswatisareecentre.in",
    url: "https://newsaraswatisareecentre.in/",
    category: "Fashion & Clothing",
    caseStudy: "newsaraswatisareecentre",
  },
  {
    slug: "legalmetrology-nagaland-gov-in",
    name: "Legalmetrology",
    domain: "legalmetrology.nagaland.gov.in",
    url: "https://legalmetrology.nagaland.gov.in/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "gajlaxmipaithani-com",
    name: "Gajlaxmi Paithani",
    domain: "gajlaxmipaithani.com",
    url: "https://gajlaxmipaithani.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "luntra-co-in",
    name: "Luntra",
    domain: "luntra.co.in",
    url: "http://luntra.co.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "shringarika-in",
    name: "Shringarika",
    domain: "shringarika.in",
    url: "https://shringarika.in/",
    category: "Gifts",
    caseStudy: null,
  },
  {
    slug: "24adsmarketing-com",
    name: "24 Ads Marketing",
    domain: "24adsmarketing.com",
    url: "https://24adsmarketing.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "sitaravastram-com",
    name: "Sitara Vastram",
    domain: "sitaravastram.com",
    url: "https://sitaravastram.com/",
    category: "Fashion & Clothing",
    caseStudy: "sitaravastram",
  },
  {
    slug: "thegrafftee-com",
    name: "The Grafftee",
    domain: "thegrafftee.com",
    url: "https://thegrafftee.com/",
    category: "Service-based",
    caseStudy: "thegrafftee",
  },
  {
    slug: "3am-assignments-com",
    name: "3am-assignments",
    domain: "3am-assignments.com",
    url: "https://3am-assignments.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "filtxpert-com",
    name: "FiltXpert",
    domain: "filtxpert.com",
    url: "https://filtxpert.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "lesbijouxdangeli-com",
    name: "Lesbijouxdangeli",
    domain: "lesbijouxdangeli.com",
    url: "https://lesbijouxdangeli.com/",
    category: "Jewelry",
    caseStudy: null,
  },
  {
    slug: "decisivefitness-in",
    name: "Decisive Fitness",
    domain: "decisivefitness.in",
    url: "https://decisivefitness.in/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "omsaigsk-in",
    name: "Omsaigsk",
    domain: "omsaigsk.in",
    url: "https://omsaigsk.in/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "aarthifashionjewellery-com",
    name: "Aarthi Fashion Jewellery",
    domain: "aarthifashionjewellery.com",
    url: "https://aarthifashionjewellery.com/",
    category: "Jewelry",
    caseStudy: null,
  },
  {
    slug: "anchalweaves-com",
    name: "Anchalweaves",
    domain: "anchalweaves.com",
    url: "https://anchalweaves.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "aquossilver-com",
    name: "Aquossilver",
    domain: "aquossilver.com",
    url: "https://aquossilver.com/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "terrestrialyt-com",
    name: "Terrestrial",
    domain: "terrestrialyt.com",
    url: "https://terrestrialyt.com/",
    category: "Custom",
    caseStudy: "terrestrialyt",
  },
  {
    slug: "sudheerktonegramgold-com",
    name: "Sudheerktonegramgold",
    domain: "sudheerktonegramgold.com",
    url: "https://sudheerktonegramgold.com/",
    category: "Jewelry",
    caseStudy: null,
  },
  {
    slug: "craftihubsartmart-in",
    name: "Craftihubsartmart",
    domain: "craftihubsartmart.in",
    url: "https://craftihubsartmart.in/",
    category: "Gifts",
    caseStudy: null,
  },
  {
    slug: "themahilaa-com",
    name: "Themahilaa",
    domain: "themahilaa.com",
    url: "https://themahilaa.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "fabonaturals-com",
    name: "Fabo Naturals",
    domain: "fabonaturals.com",
    url: "https://fabonaturals.com/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "sweatfreelife-com",
    name: "Sweatfreelife",
    domain: "sweatfreelife.com",
    url: "https://sweatfreelife.com/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "badmintonsq-com",
    name: "Badmintonsq",
    domain: "badmintonsq.com",
    url: "https://badmintonsq.com/",
    category: "Other",
    caseStudy: null,
  },
  {
    slug: "qathirsnaturals-com",
    name: "Qathir's Naturals",
    domain: "qathirsnaturals.com",
    url: "https://qathirsnaturals.com/",
    category: "Beauty & Wellness",
    caseStudy: null,
  },
  {
    slug: "punjabichaapcorner-com",
    name: "Punjabi Chaap Corner",
    domain: "punjabichaapcorner.com",
    url: "https://punjabichaapcorner.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "hmsfashionhub-com",
    name: "Hmsfashionhub",
    domain: "hmsfashionhub.com",
    url: "https://hmsfashionhub.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "kashmircart-in",
    name: "Kashmir Cart",
    domain: "kashmircart.in",
    url: "https://kashmircart.in/",
    category: "Food & Beverage",
    caseStudy: null,
  },
  {
    slug: "pamporekesar-com",
    name: "Pampore Kesar",
    domain: "pamporekesar.com",
    url: "https://pamporekesar.com/",
    category: "Food & Beverage",
    caseStudy: null,
  },
  {
    slug: "sncovers-com",
    name: "Sncovers",
    domain: "sncovers.com",
    url: "https://sncovers.com/",
    category: "Home & Decor",
    caseStudy: null,
  },
  {
    slug: "shukala-com",
    name: "Shukala",
    domain: "shukala.com",
    url: "https://shukala.com/",
    category: "Other",
    caseStudy: null,
  },
  {
    slug: "shailudigitalstore-com",
    name: "Shailudigitalstore",
    domain: "shailudigitalstore.com",
    url: "https://shailudigitalstore.com/",
    category: "Other",
    caseStudy: null,
  },
  {
    slug: "grshotblasting-com",
    name: "GR Shot Blasting",
    domain: "grshotblasting.com",
    url: "https://grshotblasting.com/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "jnnysartstudio-in",
    name: "Jnnysartstudio",
    domain: "jnnysartstudio.in",
    url: "https://jnnysartstudio.in/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "kenstto-com",
    name: "Kenstto",
    domain: "kenstto.com",
    url: "https://www.kenstto.com/",
    category: "Other",
    caseStudy: null,
  },
  {
    slug: "zarqaa-in",
    name: "Zarqaa",
    domain: "zarqaa.in",
    url: "https://zarqaa.in/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "namaskarakarnatakadigitalmedia-online",
    name: "Namaskarakarnatakadigitalmedia",
    domain: "namaskarakarnatakadigitalmedia.online",
    url: "https://namaskarakarnatakadigitalmedia.online/",
    category: "Service-based",
    caseStudy: null,
  },
  {
    slug: "craftedframes-in",
    name: "Craftedframes",
    domain: "craftedframes.in",
    url: "https://craftedframes.in/",
    category: "Gifts",
    caseStudy: null,
  },
  {
    slug: "krushidoctor-com",
    name: "Krushi Doctor",
    domain: "krushidoctor.com",
    url: "https://krushidoctor.com/",
    category: "Service-based",
    caseStudy: "krushidoctor",
  },
  {
    slug: "khyationlinemart-in",
    name: "Khyationlinemart",
    domain: "khyationlinemart.in",
    url: "https://khyationlinemart.in/",
    category: "Other",
    caseStudy: null,
  },
  {
    slug: "stylessages-com",
    name: "Stylessages",
    domain: "stylessages.com",
    url: "https://stylessages.com/",
    category: "Fashion & Clothing",
    caseStudy: null,
  },
  {
    slug: "clickngreet-in",
    name: "ClickNGreet",
    domain: "clickngreet.in",
    url: "https://clickngreet.in/",
    category: "Gifts",
    caseStudy: "clickngreet",
  },
  {
    slug: "hmsbrothers-com",
    name: "Hmsbrothers",
    domain: "hmsbrothers.com",
    url: "https://hmsbrothers.com/",
    category: "Other",
    caseStudy: null,
  },
];
