export const contactInfo = {
  name: "Ritesh Kumar Giri",
  title: "Software Engineer",
  location: "Lucknow, India",
  phone: "+91-7007436164",
  email: "rgiri5001@gmail.com",
  profileImage: "/images/pfp.png",
};

export const servicesData = [
  {
    title: "Languages",
    description: "Core programming languages I use in production.",
    items: [
      { title: "C++" },
      { title: "TypeScript" },
      { title: "JavaScript" },
      { title: "Python" },
      { title: "SQL" },
    ],
  },
  {
    title: "Frontend",
    description: "Modern interfaces focused on speed, UX, and maintainability.",
    items: [
      { title: "React.js" },
      { title: "Redux Toolkit" },
      { title: "Next.js" },
      { title: "HTML5 / CSS3" },
      { title: "Tailwind CSS" },
      { title: "Framer Motion" },
    ],
  },
  {
    title: "Backend",
    description: "Scalable APIs and real-time systems for business products.",
    items: [
      { title: "Node.js" },
      { title: "Express.js" },
      { title: "Prisma" },
      { title: "REST APIs" },
      { title: "Socket.IO" },
      { title: "Microservices" },
    ],
  },
  {
    title: "Databases",
    description: "Relational, document, vector, and in-memory storage stacks.",
    items: [
      { title: "PostgreSQL" },
      { title: "MongoDB" },
      { title: "Pinecone" },
      { title: "Redis" },
    ],
  },
  {
    title: "AI / ML",
    description: "Applied AI integrations for real-world product features.",
    items: [
      { title: "LangChain" },
      { title: "Google Gemini API" },
      { title: "Groq SDK" },
    ],
  },
  {
    title: "DevOps & Tools",
    description: "Delivery, orchestration, and collaborative engineering workflows.",
    items: [
      { title: "Git / GitHub" },
      { title: "Docker" },
      { title: "Kubernetes" },
      { title: "CI/CD (GitHub Actions)" },
      { title: "Postman" },
      { title: "VS Code" },
    ],
  },
];

export const experienceData = [
  {
    company: "CleanShip (MariBiz.ai)",
    location: "Lucknow, India",
    mode: "Hybrid",
    role: "Software Engineer",
    duration: "Mar 2026 - Present",
    highlights: [
      "Developing and maintaining a full-stack B2B maritime marketplace for complete RFQ lifecycles and vendor management.",
      "Collaborating in a hybrid team to build scalable enterprise solutions with Next.js, Node.js, Express, and PostgreSQL.",
    ],
  },
  {
    company: "NextGen Fusion",
    location: "Remote",
    mode: "Freelance",
    role: "Web Developer",
    duration: "Jan 2025 - Present",
    highlights: [
      "Develop and maintain 50+ live WordPress websites and 10+ MERN stack applications with scalable backend architecture.",
      "Orchestrate CI/CD pipelines across Vercel, Netlify, Render, AWS, and Hostinger for automated delivery.",
      "Deploy containerized production workloads using Docker and Kubernetes for consistency and reliability.",
      "Deliver end-to-end solutions including UI/UX, secure backend APIs, and complete hosting setup.",
    ],
  },
];

export const educationData = {
  institute: "Babu Banarasi Das Northern India Institute of Technology",
  degree: "Bachelor of Technology in Computer Science & Engineering",
  location: "Lucknow, India",
  duration: "2022 - Present",
};

export const certifications = [
  "Job Ready Cohort (Sheryians Coding School): Intensive full-stack training covering DSA, system design, and DevOps (Docker, CI/CD).",
  "Data Science - AI & DSA (ShapeMySkills): Completed a 90-hour program focused on AI algorithms, machine learning, and Python.",
];

export const achievements = [
  "1st Prize Winner, Utkarsh 2022 Photography Competition.",
  "Cleared Indian Air Force Exam.",
];

export const leadership = [
  "Coordinator, Discipline Team at BBDNIIT.",
];

export const projects = [
  {
    id: 1,
    name: "MariBiz - Global Marine Services & RFQ Marketplace",
    description:
      "Built a full-stack maritime marketplace with RFQ posting, quote submission, role-based approvals, Socket.IO chat, analytics, and automated transactional emails.",
    liveUrl: "https://maribiz.ai",
    repoUrl: "https://github.com/ritesh5001",
    image: "/assets/projects/mobile-accessories-store.jpg",
    bgImage: "/assets/backgrounds/blanket.jpg",
    frameworks: [
      { id: 1, name: "Next.js" },
      { id: 2, name: "Node.js" },
      { id: 3, name: "Express" },
      { id: 4, name: "Prisma" },
      { id: 5, name: "PostgreSQL" },
      { id: 6, name: "Socket.IO" },
    ],
  },
  {
    id: 2,
    name: "Tat Vivah - Multi-Vendor Wedding E-Commerce",
    description:
      "Engineered a scalable multi-vendor commerce platform with JWT RBAC, real-time inventory, atomic checkout, Redis caching, and layered monolith architecture.",
    liveUrl: "https://tatvivahtrends.com",
    repoUrl: "https://github.com/ritesh5001",
    image: "/assets/projects/plant-shop.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "TypeScript" },
      { id: 2, name: "Node.js" },
      { id: 3, name: "Prisma" },
      { id: 4, name: "PostgreSQL" },
      { id: 5, name: "Redis" },
    ],
  },
  {
    id: 3,
    name: "Explore Fusion - AI-Powered Travel Microservices App",
    description:
      "Architected a microservices-based travel ecosystem with API gateway, Groq AI trip planning, travel buddy matching, social feed, and real-time Socket.IO messaging.",
    liveUrl: "https://explorefusion.online",
    repoUrl: "https://github.com/ritesh5001",
    image: "/assets/projects/apple-tech-store.jpg",
    bgImage: "/assets/backgrounds/map.jpg",
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "Node.js" },
      { id: 3, name: "Socket.IO" },
      { id: 4, name: "Microservices" },
      { id: 5, name: "Groq SDK" },
      { id: 6, name: "JWT" },
    ],
  },
  {
    id: 4,
    name: "JARVIS AI - Full-Stack AI Chat Platform",
    description:
      "Developed an AI chat platform with secure JWT auth, long-term conversational memory via Pinecone, and context-aware responses using Google Gemini API.",
    liveUrl: "https://jarvisai.riteshgiri.dev",
    repoUrl: "https://github.com/ritesh5001",
    image: "/assets/projects/electronics-store.jpg",
    bgImage: "/assets/backgrounds/poster.jpg",
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "Node.js" },
      { id: 3, name: "Express" },
      { id: 4, name: "Pinecone" },
      { id: 5, name: "Gemini API" },
    ],
  },
];

export const clientProjects = [
  {
    id: "tatvivahtrends",
    slug: "tatvivahtrends",
    featured: true,
    name: "TatVivah Trends",
    tagline: "Premium Ethnic Wedding Wear Marketplace",
    domain: "tatvivahtrends.com",
    liveUrl: "https://tatvivahtrends.com",
    role: "Full-Stack Developer",
    type: "Next.js / Full-Stack",
    description:
      "Built Next.js marketplace for ethnic wear with 3000+ products including sherwanis, kurtas, and Modi jackets. Implemented occasion-based filtering for wedding, haldi, and mehendi events. Integrated verified seller system, Razorpay payments, and 10-day returns. Created product showcase, gift cards, and mobile-responsive design for premium wedding fashion.",
    deliverables: [
      "Next.js Marketplace Development",
      "Multi-Vendor Platform Architecture",
      "Occasion-Based Product Filtering",
      "Razorpay Payment Gateway Integration",
      "Wedding Fashion E-Commerce",
    ],
    tech: ["Next.js", "TypeScript", "Node.js", "Razorpay", "PostgreSQL", "Prisma"],
    images: [
      "/assets/projects/tatvivahtrends/1.png",
      "/assets/projects/tatvivahtrends/2.png",
      "/assets/projects/tatvivahtrends/3.png",
    ],
  },
  {
    id: "maribiz",
    slug: "maribiz",
    featured: true,
    name: "MariBiz",
    tagline: "Global Marine Procurement Marketplace Platform",
    domain: "maribiz.ai",
    liveUrl: "https://maribiz.ai",
    role: "Full-Stack Developer",
    type: "Next.js / Full-Stack",
    description:
      "Built global marine procurement marketplace connecting 3,226+ vendors with shipowners. Implemented RFQ system with vendor verification and real-time messaging. Created vendor profiles across 121 categories including maintenance, spare parts, hull cleaning, and crew transport. Integrated quote comparison and port service discovery for the maritime industry.",
    deliverables: [
      "B2B Marketplace Development",
      "RFQ & Vendor Management System",
      "Real-Time Communication Features",
      "Port & Service Discovery Platform",
      "Maritime Industry Solutions",
    ],
    tech: ["Next.js", "Node.js", "Express", "PostgreSQL", "Socket.IO", "Prisma"],
    images: [
      "/assets/projects/maribiz/1.png",
      "/assets/projects/maribiz/2.png",
      "/assets/projects/maribiz/3.png",
    ],
  },
  {
    id: "hcbengineering",
    slug: "hcbengineering",
    featured: false,
    name: "HCB Engineering",
    tagline: "Electrical Solutions Website Development",
    domain: "hcbengineering.in",
    liveUrl: "https://hcbengineering.in",
    role: "Full-Stack Developer",
    type: "WordPress",
    description:
      "Developed a comprehensive website for HCB Engineering, a government-licensed electrical contracting company with 20+ years of experience. Created a professional online presence showcasing commercial, residential, and specialty electrical services. Implemented responsive design, service portfolio pages, client testimonials, and contact forms for lead generation.",
    deliverables: [
      "Website Development",
      "Responsive Web Design",
      "WordPress Development",
      "Contact Form Integration",
      "Service Portfolio Showcase",
    ],
    tech: ["WordPress", "PHP", "HTML5", "CSS3", "JavaScript"],
    images: ["/assets/projects/hcbengineering/1.png"],
  },
  {
    id: "samaraha",
    slug: "samaraha",
    featured: false,
    name: "Samaraha",
    tagline: "Premium Silk Saree E-Commerce Platform",
    domain: "samaraha.com",
    liveUrl: "https://samaraha.com",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Developed a sophisticated e-commerce platform specializing in premium traditional silk sarees including Banarasi, Tussar, and Hand Printed varieties. Built a comprehensive WooCommerce shopping experience with advanced product filtering, 25+ SKU catalog, wishlist, comparison, and cart functionality. Integrated UPI and digital wallet payment gateways with SSL-secured checkout.",
    deliverables: [
      "WooCommerce E-Commerce Development",
      "Product Catalog & Inventory Management",
      "Responsive UI/UX Design",
      "Payment Gateway Integration",
      "SSL Security & Checkout Optimization",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/samaraha/1.png"],
  },
  {
    id: "thegrafftee",
    slug: "thegrafftee",
    featured: false,
    name: "The Grafftee",
    tagline: "HR & Talent Acquisition Platform Website",
    domain: "thegrafftee.com",
    liveUrl: "https://thegrafftee.com",
    role: "Full-Stack Developer",
    type: "WordPress",
    description:
      "Developed a comprehensive HR and talent acquisition platform for Grafftee, India's leading recruitment and workforce solutions company. Built multi-feature web application showcasing talent acquisition, virtual HR support, payroll management, and employee experience tools. Implemented interactive service modules, demo booking systems, and candidate placement pages.",
    deliverables: [
      "Full-Stack Web Development",
      "Responsive Web Design",
      "HR Platform Development",
      "Form Integration & Automation",
      "Service Module Architecture",
    ],
    tech: ["WordPress", "PHP", "JavaScript", "HTML5", "CSS3"],
    images: ["/assets/projects/thegrafftee/1.png"],
  },
  {
    id: "saurally",
    slug: "saurally",
    featured: false,
    name: "Saurally Solar",
    tagline: "Renewable Energy E-Commerce Platform",
    domain: "saurally.com",
    liveUrl: "https://saurally.com",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built a WooCommerce solar platform for Saurally Solar featuring 40+ products. Implemented product filtering, comparison tools, and dynamic pricing. Integrated multi-gateway payments including UPI, cards, and net banking. Built wishlist and WhatsApp support features. Created mobile-optimized design with free shipping and delivery tracking.",
    deliverables: [
      "WooCommerce Development",
      "Solar Product Catalog Design",
      "Multi-Gateway Payment Integration",
      "Advanced Product Filtering",
      "Customer Support Integration",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/saurally/1.png"],
  },
  {
    id: "terrestrialyt",
    slug: "terrestrialyt",
    featured: false,
    name: "TerrestrialYT",
    tagline: "Gaming & Anime E-Commerce Store",
    domain: "terrestrialyt.com",
    liveUrl: "https://terrestrialyt.com",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built WooCommerce store for TerrestrialYT featuring gaming and anime merchandise including mousepads, posters, tapestries, tote bags, and coasters. Implemented product variations, dynamic pricing, and wishlist functionality. Integrated social media links for Instagram, YouTube, Twitch, and Discord. Created responsive mobile design with secure checkout and global shipping support.",
    deliverables: [
      "WooCommerce E-Commerce Development",
      "Product Variations & Variants Management",
      "Social Media Integration",
      "Community Forum Integration",
      "Merchandise Store Design",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/terrestrialyt/1.png"],
  },
  {
    id: "newsaraswatisareecentre",
    slug: "newsaraswatisareecentre",
    featured: false,
    name: "New Saraswati Saree Centre",
    tagline: "Handwoven Textiles E-Commerce Store",
    domain: "newsaraswatisareecentre.in",
    liveUrl: "https://newsaraswatisareecentre.in",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built WooCommerce saree marketplace featuring 40+ handwoven products including cotton, muslin, and paithani varieties. Implemented product filtering, dynamic pricing, and secure checkout. Integrated multi-gateway payments, wishlist, and product comparison tools. Created festive collection pages, customer testimonials, and mobile-optimized design with free shipping.",
    deliverables: [
      "WooCommerce Development",
      "Traditional Textile E-Commerce",
      "Multi-Gateway Payment Integration",
      "Festive Collection Management",
      "Mobile-Responsive Design",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/newsaraswatisareecentre/1.png"],
  },
  {
    id: "sitaravastram",
    slug: "sitaravastram",
    featured: false,
    name: "Sitara Vastram",
    tagline: "Premium Limited-Piece Ethnic Wear Store",
    domain: "sitaravastram.com",
    liveUrl: "https://sitaravastram.com",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built WooCommerce ethnic wear store featuring limited collections across festive, everyday, and exclusive categories. Implemented product variants, dynamic pricing, and a style video section with 6+ reels. Integrated testimonials, WhatsApp support, and wishlist functionality. Designed mobile-responsive interface with free shipping, COD, and secure checkout.",
    deliverables: [
      "WooCommerce E-Commerce Development",
      "Limited-Edition Collection Management",
      "Style Video Integration",
      "WhatsApp Business Integration",
      "Premium Fashion Store Design",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/sitaravastram/1.png"],
  },
  {
    id: "clickngreet",
    slug: "clickngreet",
    featured: false,
    name: "ClickNGreet",
    tagline: "Personalized Gift Shop & Marketplace",
    domain: "clickngreet.in",
    liveUrl: "https://clickngreet.in",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built WooCommerce gift store with 20+ categories including frames, mugs, T-shirts, and resin art. Implemented product variants, pricing, filtering, and occasion-based shopping. Integrated testimonials, WhatsApp support, and bulk order management. Designed mobile-first interface with fast delivery, seamless checkout, and pan-India shipping.",
    deliverables: [
      "WooCommerce E-Commerce Development",
      "Multi-Category Gift Marketplace",
      "Occasion-Based Product Filtering",
      "Bulk Order Management System",
      "Personalized Product Showcase",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/clickngreet/1.png"],
  },
  {
    id: "krushidoctor",
    slug: "krushidoctor",
    featured: false,
    name: "Krushi Doctor",
    tagline: "Agri Guidance & Farming Platform",
    domain: "krushidoctor.com",
    liveUrl: "https://krushidoctor.com",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built WooCommerce agricultural platform with 100+ products including crop schedules and sticky traps. Implemented crop PDF guides with WhatsApp support. Created categories for insecticides, fertilizers, and equipment. Integrated farmer testimonials and blog. Designed mobile interface with 24/7 support, free shipping, and easy returns serving 1.2 lakh+ farmers.",
    deliverables: [
      "WooCommerce Agricultural Platform Development",
      "Crop Schedule & Digital Guidance System",
      "Multi-Category Agricultural Products Management",
      "WhatsApp Integration & Support System",
      "Farmer Community & Testimonial Platform",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/krushidoctor/1.png"],
  },
  {
    id: "kalamohini",
    slug: "kalamohini",
    featured: false,
    name: "Kalamohini",
    tagline: "Traditional Art & Ethnic Fashion Store",
    domain: "kalamohini.in",
    liveUrl: "https://kalamohini.in",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Built a WooCommerce-powered e-commerce platform for Kalamohini, a traditional Indian art and ethnic fashion brand. Implemented product catalog management with dynamic pricing, advanced filtering, and mobile-responsive design. Integrated multiple payment gateways, wishlist functionality, and seamless checkout for a premium shopping experience.",
    deliverables: [
      "WooCommerce E-Commerce Development",
      "Product Catalog Management",
      "Mobile-Responsive Design",
      "Payment Gateway Integration",
      "Brand Identity & UI Design",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/kalamohini/1.png"],
  },
  {
    id: "mahhika",
    slug: "mahhika",
    featured: false,
    name: "Mahhika",
    tagline: "Premium Fashion & Lifestyle Store",
    domain: "mahhika.com",
    liveUrl: "https://mahhika.com",
    role: "Full-Stack Developer",
    type: "WooCommerce",
    description:
      "Developed a sophisticated WooCommerce fashion store for Mahhika, a premium lifestyle and fashion brand. Created an elegant product showcase with advanced filtering, wishlist functionality, product variation management, and seamless multi-gateway payment processing for a premium online shopping experience.",
    deliverables: [
      "WooCommerce E-Commerce Development",
      "Premium Fashion Store Design",
      "Product Variants Management",
      "Wishlist & Comparison Features",
      "Responsive Mobile Design",
    ],
    tech: ["WooCommerce", "WordPress", "PHP", "JavaScript", "CSS3"],
    images: ["/assets/projects/mahhika/1.png"],
  },
];

export const socials = [
  {
    name: "LinkedIn",
    href: "https://linkedin.com/in/ritesh5001",
  },
  {
    name: "GitHub",
    href: "https://github.com/ritesh5001",
  },
  {
    name: "Email",
    href: "mailto:rgiri5001@gmail.com",
  },
];
